require("core.plugin_config.nvim-tree")
require("core.plugin_config.lualine")
require("core.plugin_config.gruvbox")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.lspconfig")
-- require("core.plugin_config.codeium")
require("core.plugin_config.nvterm")
require("core.plugin_config.null-ls")
require("core.plugin_config.bufferline")
